---
- name: gather os specific variables
  #include_vars: main.yml
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}.yml"
  tags: vars


- homebrew:
    name: vim
    state: "{{ role_state['package'] }}"

