---
- name: gather os specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}.yml"
  tags: vars

- dnf:
    name: vim-enhanced
    state: "{{ role_state['package'] }}"

